package com.amigos.awsuploadimage.enumeration;

public enum AuthenticateStatus {
    INVALID_CREDENTIAL,
    INVALID_LOGIN_ID,
    INVALID_EMAIL,
    PASSWORD_ERROR_COUNT_EXCEED,
    OTP_REGISTER_SUCCESS,
    AUTHENTICATED,
    OTP_REQUIRED,
    OTP_REGISTER,
    INVALID_OTP,
    CHANGE_PASSWORD_REQUIRED,
    CHANGE_PASSWORD_FAILED,
    SUCCESS,
    SMS_OTP_REQUIRED,
    SMS_OTP_INVALID,
    SMS_OTP_EXPIRE,
    UNAUTHENTICATED
}
